var ClassColumn = false;
var ProjectColumn = false;
$(document).ready(function () {
    $('#overlay').fadeIn();

    $("#tbl_PettyCashList tbody tr").find("td:eq(0)").attr('title', 'click me to view detail');
    $("#tbl_PettyCashList tbody tr").find("td:eq(0)").css({ cursor: 'pointer', color: 'blue', 'text-decoration': 'underline', });
    $("#btnSave").on('click', function () {
        ValidateAccount();
    })

    $('#tbl_PettyCashList tbody tr').on('click', ' td:eq(0)', function () {
        jQuery('#PettyCashList').hide();
        $("#btnEdit").show();
        $("#btnDelete").show();
        jQuery('#PettyCashVoucher').show();
        DisablePettyCashVoucher();
    });
    $("#PettyCashVoucher").hide();
    $("#PettyCashVoucherOnEdit").hide();
    $("#PettyCashList").show();
    $("#tbl_PettyCashList").DataTable({
        dom: 'Bfrtip',
        buttons: [
    {
        extend: 'excel', text: 'Export',
        exportOptions: {
            columns: ':visible',
            orthogonal: {
                display: ':null'
            }
        }
    },

              {
                  extend: 'print',
                  exportOptions:{orthogonal:'print'},
                  title: 'Print The Report From Petty Cash ',
                  message: 'print It and Use it ',
                  customize: function (win) {
                      $(win.document.body).append('<h1> This Report was Generated by Nahid Ali</h1>'); //after the table
                      $(win.document.body).prepend('<h3>Company Name : Turf.</h3>'); //before the table
                      $(win.document.body)
                          .css('font-size', '10pt')
                      $(win.document.body).find('table')
                          .addClass('compact')
                          .css('font-size', 'inherit');
                  }
              }

     //'excel', 'pdf'
        ],
        columnDefs: [{
            targets: 4,
            render: $.fn.dataTable.render.ellipsis(5)
        }],
        pageLength: '4',
        "filter": true, // this is for disable filter (search box)
        "order": [[3, "desc"]],
        "pagingType": "full_numbers",
    });
    AddFirstRow_PettyCashVoucher(ClassColumn,ProjectColumn);
    AddRow_PettyCash();
    //GetAccount();
    $('#overlay').fadeOut();
});
function GetAccount() {
    
    $.ajax({
        url: 'http://localhost:20037/api/Expense/GetAccount',
        type: "GET",
        success: function (ApiResponse) {
            if (ApiResponse) {
                
                var response = JSON.parse(ApiResponse);
                //var id = $("#tab_PettyCash tbody tr").length-1;
                //$('#ddlAccount'+id).append($('<option></option>').val("0").text("Select"));
                var id = $("#tab_PettyCash tbody tr");

                $(id).find('.selectAccount').append($('<option></option>').val("0").text("Select"));
                var Account = "";
                for (var i = 0; i < response.length ; i++) {
                    Account += '<option value="' + response[i].ID + '">' + response[i].Code + ' | ' + response[i].Name + '</option>';
                }
                //$('#ddlAccount'+id).append(Account)
                $(id).find('.selectAccount').append(Account);
            }
        }

    })
}
function AddFirstRow_PettyCashVoucher() {


    if (ProjectColumn)
        $('#tab_PettyCash tr ').find('th:eq(4)').show();
    else
        $('#tab_PettyCash tr ').find('th:eq(4)').remove();
    
    if (ClassColumn) 
        $('#tab_PettyCash tr ').find('th:eq(3)').show();
    else
        $('#tab_PettyCash tr ').find('th:eq(3)').remove();
   
   

    
    var id = $("#tab_PettyCash tbody tr").length;
    row = '<tr id="row' + id + '" data-id="' + id + '">';
    row += '<td data-name="sel"><div id="Acount"><select  name="Account1" class="form-control selectAccount"></select></div></td>';
    row += '<td data-name="td_Amount"><input type="number" name="txtAmount1" id="txtAmount' + id + '"  class="form-control txtAmount" onkeyup="sumAmountAccount()" /></td>';
    row += '<td data-name="td_Memo"><input type="text" name="Memo1" id="txtMemo' + id + '" class="form-control memo" /></td>';
  
  if (ClassColumn)
        row += '<td data-name="sel"><div id="div_Class"><select id="ddlClass' + id + '" name="Class1"  class="form-control selectClass "><option value="0">Select</option><option value="1">Class1</option><option value="2">Class2</option><option value="3">Class3</option></select></div></td>';
  if (ProjectColumn)
        row += '<td data-name="sel"><div id="td_project"><select id="ddlProject_PettyCash' + id + '"  name="Project1" class="form-control selectProject"><option value="0">Select</option><option value="1">Project1</option><option value="2">Project2</option><option value="3">Project3</option></select></div></td>';

    row += '<td data-name="del"><button type="button" class="btn btn-danger  row-remove" id="btnRemoveRow' + id + '" onclick="removePettyCashRow(this);"  ><span aria-hidden="true">×</span></button></td>';
    row += '</tr>';
    $('#tab_PettyCash tbody').append(row);
    GetAccount();

    
    $('.selectClass').select2({}).on('select2:open', function () {
        var a = $(this).data('select2');
        if (!$('.select2-link').length) {
            a.$results.parents('.select2-results')
                    .prepend('<div class="select2-link"><a style="font-weight:bold;"> + Add New</a></div>')
                    .on('click', function (b) {
                        $(".selectClass").select2('close');
                        $('#AddClass').modal();
                    });
        }
    });
    $('.selectAccount').select2({}).on('select2:open', function () {
        var a = $(this).data('select2');
        if (!$('.select2-link').length) {
            a.$results.parents('.select2-results')
                    .prepend('<div class="select2-link"><a style="font-weight:bold;"> + Add New</a></div>')
                    .on('click', function (b) {
                        
                        $(".selectAccount").select2('close');
                        $('#AddAccount').modal();
                    });
        }
    });
    $('.selectProject').select2({}).on('select2:open', function () {
        var a = $(this).data('select2');
        if (!$('.select2-link').length) {
            a.$results.parents('.select2-results')
                    .prepend('<div class="select2-link"><a style="font-weight:bold;"> + Add New</a></div>')
                    .on('click', function (b) {
                        $(".selectProjectForExpense").select2('close');
                        $('#AddProject').modal();
                    });
        }
    });
    $('select').select2({ width: '100%' });
    
    $("#tab_PettyCash tbody tr").find("td button.row-remove").on("click", function () {
        if ($("#tab_PettyCash tbody tr").length == 1) {
            $('#div_totalAmount').hide();
        }
        $(this).closest("tr").remove();
        //sumAmountAccount();
    });
}
function AddRow_PettyCash() {
    $("#add_row").on("click", function () {
        if ($("#btnEdit")[0].style.display == "") {
            return
        }
        else {

            if (ClassColumn)
                $('#tab_PettyCash tr ').find('th:eq(3)').show();
            else
                $('#tab_PettyCash tr ').find('th:eq(3)').hide();

            if (ProjectColumn)
                $('#tab_PettyCash tr ').find('th:eq(4)').show();
            else
                $('#tab_PettyCash tr ').find('th:eq(4)').hide();


            var id = $("#tab_PettyCash tbody tr").length;
            row = '<tr id="row' + id + '" data-id="' + id + '">';
            row += '<td data-name="sel"><div id="Acount"><select style="width:200px;" name="Account1" class="form-control selectAccount"></select></div></td>';
            
            row += '<td data-name="td_Amount"><input type="number" name="txtAmount1" id="txtAmount' + id + '"  class="form-control txtAmount" onkeyup="sumAmountAccount() "/></td>';
            row += '<td data-name="td_Memo"><input type="text" name="Memo1" id="txtMemo' + id + '" class="form-control memo" /></td>';
            if ($('#tab_PettyCash tr ').find('th:eq(3)')[0].style.display = '')
                row += '<td data-name="sel"><div id="div_Class"><select id="ddlClass' + id + '"style="width:160px;" name="Class1"  class="form-control selectClass "><option value="0">Select</option><option value="1">Class1</option><option value="2">Class2</option><option value="3">Class3</option></select></div></td>';
            if ($('#tab_PettyCash tr ').find('th:eq(3)')[0].style.display = '')
                row += '<td data-name="sel"><div id="td_project"><select id="ddlProject_PettyCash' + id + '" style="width:160px;" name="Project1" class="form-control selectProject"><option value="0">Select</option><option value="1">Project1</option><option value="2">Project2</option><option value="3">Project3</option></select></div></td>';
           

            row += '<td data-name="del"><button type="button" class="btn btn-danger  row-remove" id="btnRemoveRow' + id + '" onclick="removePettyCashRow(this);"   ><span aria-hidden="true">×</span></button></td>';
            row += '</tr>';
            $('#tab_PettyCash tbody').append(row);
            GetAccount();
            //AddFirstRow_PettyCashVoucher()
            $('.selectClass').select2({}).on('select2:open', function () {
                var a = $(this).data('select2');
                if (!$('.select2-link').length) {
                    a.$results.parents('.select2-results')
                            .prepend('<div class="select2-link"><a style="font-weight:bold;"> + Add New</a></div>')
                            .on('click', function (b) {
                                $(".selectClass").select2('close');
                                $('#AddClass').modal();
                            });
                }
            });
            $('.selectAccount').select2({}).on('select2:open', function () {
                var a = $(this).data('select2');
                if (!$('.select2-link').length) {
                    a.$results.parents('.select2-results')
                            .prepend('<div class="select2-link"><a style="font-weight:bold;"> + Add New</a></div>')
                            .on('click', function (b) {
                                
                                $(".selectAccount").select2('close');
                                $('#AddAccount').modal();
                            });
                }
            });
            $('.selectProject').select2({}).on('select2:open', function () {
                var a = $(this).data('select2');
                if (!$('.select2-link').length) {
                    a.$results.parents('.select2-results')
                            .prepend('<div class="select2-link"><a style="font-weight:bold;"> + Add New</a></div>')
                            .on('click', function (b) {
                                $(".selectProjectForExpense").select2('close');
                                $('#AddProject').modal();
                            });
                }
            });
        }

        $("#div_totalAmount").show();
        $("#lblTotalAmount").text('0.00');
        });
    
}
function openPettyCashVoucher() {
    $("#btnEdit").hide();
    $("#btnDelete").hide();
    jQuery('#PettyCashList').hide();
    jQuery('#PettyCashVoucher').show();

}
function removePettyCashRow(btn) {
    
    tr = $(btn).closest('tr');
    if ($("#tab_PettyCash tbody tr").length == 1) {
        $("#div_totalAmount").hide();
    }
    tr.remove();
    sumAmountAccount();

}
function show_confirm_LeaveWithoutSavingPettyCash(message) {
    swal({
        title: 'Are you sure want to leave WithOut Saving?',
        //text: message,
        icon: "warning",
        buttons: ["No", "Yes"],
    }).then((ifyes) => {
        if (ifyes) {
            $('#tab_PettyCash tbody tr').remove();
            AddFirstRow_PettyCashVoucher();
            $('#PettyCashList').show();
            $('#PettyCashVoucher').hide();

        }
    });

}

function hide_showPettyCashColumn() {
    $('#tab_PettyCash tr').each(function () {
        
        if (ClassColumn) {

            $('#tab_PettyCash tr ').find('th:eq(3)').show();
            $('#tab_PettyCash tr ').find('td:eq(3)').show();
        } else {
            $('#tab_PettyCash tr ').find('th:eq(3)').hide();
            $('#tab_PettyCash tr ').find('td:eq(3)').hide();

        }
        if (ProjectColumn) {

            $('#tab_PettyCash tr ').find('th:eq(4)').show();
            $('#tab_PettyCash tr ').find('td:eq(4)').show();
        } else {
            $('#tab_PettyCash tr ').find('th:eq(4)').hide();
            $('#tab_PettyCash tr ').find('td:eq(4)').hide();

        }
    });

}
function sumAmountAccount() {
    var sum = 0;
    $('.txtAmount').each(function () {
        if ($(this).val() != '')
            sum = parseFloat(sum) + parseFloat($(this).val());
    });

    $('#lblTotalAmount').html(sum.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 }));
}
function ValidateAccount() {
    RowID = tr = $("#tab_PettyCash tbody tr")[0].getAttribute('id');
    rowNo = RowID.replace('row', '');
    isValid = false;
    $(".selectAccount").each(function () {
        if ($(this).val() != 0) {
            isValid = true;
        }
        else {
            showMessage('please select account', 'danger', '');
            isValid = false;
            $("#ddlAccount" + rowNo)[0].focus();
            return false;
        }
        rowNo++;
    });
    if (isValid)
        ValidateAmount()
    //ValidateMemo();
}
function ValidateAmount() {
    RowID = tr = $("#tab_PettyCash tbody tr")[0].getAttribute('id');
    rowNo = RowID.replace('row', '');
    isValid = false;
    $(".txtAmount").each(function () {
        if ($(this).val().match(RegexForInteger)) {
            isValid = true;
        }
        else {
            showMessage('please Enter Amount', 'danger', '');
            isValid = false;
            $("#txtAmount" + rowNo)[0].focus();
            return false;
        }
        rowNo++;
    });
    if (isValid)
        ValidateMemo();


}
function ValidateMemo() {
    
    RowID = tr = $("#tab_PettyCash tbody tr")[0].getAttribute('id');
    rowNo = RowID.replace('row', '');
    isValid = false;
    $(".memo").each(function () {
        if ($(this).val() != "") {
            isValid = true;
        }
        else {
            showMessage('please Enter Memo', 'danger', '');
            isValid = false;
            $("#txtMemo" + rowNo)[0].focus();
            return false;
        }
        rowNo++;
    });
    if (isValid) {
        show_confirm();
    }
}
function show_confirm(message) {
    swal({
        title: "Do You Wish To",
        icon: "warning",
        buttons: {
            cancel: "Cancel",
            SaveAndPrint: "Save And Print",
            SaveOnly: "Save Only",
        },
    }).then((ifyes) => {
        if (ifyes) {
            
            //$("#ExpenseVoucher").hide();
            //$("#ExpenseVoucherEdit").hide();
            //jQuery('#div_ExpList').show();// Allow next click to succeed
            showMessage('Data Saved Successfully', 'success', '');
            setTimeout(function () { window.location.href = "http://localhost:42985/PettyCash.aspx"; }, 3000);
        }
    });
}
function DisablePettyCashVoucher() {

    $('#PettyCashVoucher').find('input, textarea, button, select').attr('disabled', true);
    $("#PettyCashVoucher").find('select').select2('destroy');
    $('#PettyCashVoucher').find('input, textarea, button,select').css({ 'cssText': 'background: #dddddd !important' });
    $('#PettyCashVoucher').find(('.datepicker:input[type="text"]')).prop('disabled', true);
    $('.gj-icon').hide();
    $('a').attr('disabled', true);
    $("#btnEdit").attr('disabled', false);
    $("#btnEdit").css({ 'cssText': 'background:' })
}
function EnablePettyCashVoucher() {
    
    $('#PettyCashVoucher').find('input, textarea, button, select').attr('disabled', false);
    $("#PettyCashVoucher").find('select').select2();
    $('#PettyCashVoucher').find('input, textarea, button,select').css({ 'cssText': 'background:' });
    $('#PettyCashVoucher').find(('.datepicker:input[type="text"]')).prop('disabled', false);
    $('.gj-icon').hide();
    $('a').attr('disabled', false);
    $("#btnEdit").hide();
    $("#txtVoucherNo").attr('disabled', true);
    $("#txtVoucherNo").css({ 'cssText': 'background: #dddddd !important' });
    $('#PettyCashVoucher').find(('#VoucherDate:input[type="text"]')).prop('disabled', true);
    $('#PettyCashVoucher').find(('#VoucherDate:input[type="text"]')).css({ 'cssText': 'background: #dddddd !important' });
    var iconclass = $("#PettyCashVoucher").find('input[type="text"][id="VoucherDate"]').next().addClass('abc')[0].getAttribute('class');
    $("." + iconclass.replace('gj-icon ', '')).hide();
}
function show_confirm_RemoveAllRowsFromPettyCash(message) {
    if ($('#tab_PettyCash tbody tr').length != 0) {
        swal({
            title: 'Are you sure want to remove all lines?',
            //text: message,
            icon: "warning",
            buttons: ["No", "Yes"],
        }).then((ifyes) => {
            if (ifyes) {
                $('#tab_PettyCash tbody tr').remove();
                $('#div_totalAmount').hide();
                //$("#lblTotal").text('0.00');
            }
        });
    }
}