
$(document).ready(function () {
  
    $(function () {
        
        $('#myTab a:last').tab('show');
    });

    $('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
        
        var target = $(e.target).attr("href");
        if ((target == '#Inventory')) {

        } else {
            if ($('#ddlType')[0].getAttribute('disabled') != 'disabled')
                return;
            else {

                Reset_InventoryForm();
                Reset_Non_InventoryForm();
                ResetServiceForm();
                EnableInventory();
                EnableNon_Inventory();
                EnableServices();
                $('#ddlType').attr('disabled', false);
                $("#ddlType").css({ 'cssText': 'background : ' });
                $('#ddlType').select2()[0].selectedIndex = 0;
                $('#ddlType').select2().val("0");
                $('#ddlType').select2({ width: '100%' });
                $('#Add_NonInventory').hide();
                $('#Add_Services').hide();
                $('#Add_Inventory').hide();
                $("#btnDeleteInventory").hide();
                $("#btnDeleteNonInventory").hide();
                $("#btnDeleteService").hide();

            }
        }
    });


    $("#tblProductAndServices tbody tr").find("td:eq(2)").attr('title', 'click me to view detail');
    $("#tblProductAndServices tbody tr").find("td:eq(2)").css({ cursor: 'pointer', color: 'blue', 'text-decoration': 'underline', 'title': 'click and show detail' });
    var params = getUrlParameter('param');
    if (params) {
        $('.nav-tabs a[href="#Inventory"]').tab('show');
        setTimeout(function () { $('#ddlType').val(1).change(); }, 0);
    }
    $(".select2").select2();
    $('.Catagory').select2({}).on('select2:open', function () {
        var a = $(this).data('select2');
        if (!$('.select2-link').length) {
            a.$results.parents('.select2-results')
                    .prepend('<div class="select2-link"><a style="font-weight:bold;"> + Add New</a></div>')
                    .on('click', function (b) {
                        $(".Catagory").select2('close');
                        $('#AddCatagory').modal();
                    });
        }
    });

    $('.Account').select2({}).on('select2:open', function () {
        var a = $(this).data('select2');
        if (!$('.select2-link').length) {
            a.$results.parents('.select2-results')
                    .prepend('<div class="select2-link"><a style="font-weight:bold;"> + Add New</a></div>')
                    .on('click', function (b) {
                        $(".Account").select2('close');
                        $('#AddAccount').modal();
                    });
        }
    });
    $('.vendor').select2({}).on('select2:open', function () {
        var a = $(this).data('select2');
        if (!$('.select2-link').length) {
            a.$results.parents('.select2-results')
                    .prepend('<div class="select2-link"><a style="font-weight:bold;"> + Add New</a></div>')
                    .on('click', function (b) {
                        $(".vendor").select2('close');
                        $('#AddVenderModel').modal();
                    });
        }
    });
    $('#tblProductAndServices tbody tr').on('click', ' td:eq(2)', function () {
        // 
        //var tabID= $("#my_tab").find('li[class="active"]').children()[0].getAttribute('href');
        type = $(this)[0].textContent;
        if (type == "Inventory")
            DisableInventory();
        else if (type == "Non Inventory")
            DisableNon_Inventory();
        else
            DisableServices();
        $('.nav-tabs a[href="#Inventory"]').tab('show');
        $("#btnEditInventory").show();
        $("#btnDeleteInventory").show();
        var ID = 0;
        $("#ddlType option").each(function () {
            var Type = $(this).text();
            if (type == Type) {
                var Val = $(this).val();
                ID = Val;
            }


        })
        //$("#ddlType option").ea
        $('#ddlType').val(ID).change();

    });
    $('#Add_NonInventory').hide();
    $('#Add_Services').hide();
    $('#Add_Inventory').hide();
    $("#tblProductAndServices").DataTable({
        dom: 'Bfrtip',
        buttons: [
            {
                extend: 'excel', text: 'Export',
                exportOptions: {
                    columns: ':visible',
                    orthogonal: {
                        display: ':null'
                    }
                }
            },
              {
                  extend: 'print',
                  exportOptions: { orthogonal: 'print' },
                  title: 'Print The Report From  product and Services ',
                  message: 'print It and Use it ',
                  customize: function (win) {
                      $(win.document.body).append('<h1> This Report was Generated by Nahid Ali</h1>'); //after the table
                      $(win.document.body).prepend('<h3>Company Name : Turf.</h3>'); //before the table
                      $(win.document.body)
                          .css('font-size', '10pt')
                      $(win.document.body).find('table')
                          .addClass('compact')
                          .css('font-size', 'inherit');
                  }
              }
             //'excel', 'pdf'
        ],
        columnDefs: [{
            targets: [4, 7, 8],
            render: $.fn.dataTable.render.ellipsis(7)
        }],
        pageLength: '4',
        "filter": true, // this is for disable filter (search box)
        "order": [[3, "desc"]],
        "pagingType": "full_numbers",
        "scrollX": true
    });
    $('#overlay').fadeOut();
})
function OnChangeType() {
    dd = document.getElementById('ddlType');
    if (dd.selectedOptions[0].value == '0') {
        $('#Add_NonInventory').hide();
        $('#Add_Services').hide();
        $('#Add_Inventory').hide();
        //  $('#Add_Services').hide();
    }
    if (dd.selectedOptions[0].value == '1') {
        $('#Add_NonInventory').hide();
        $('#Add_Services').hide();
        $('#Add_Inventory').show();
        $("#txtAsOFDate_Inventory").attr('disabled', 'disabled');
        $("#txtAsOFDate_Inventory").css({ 'cssText': 'background: #dddddd !important' });
        $('#txtAsOFDate_Inventory').next().hide();
        $('#txtAsOFDate_Inventory').val('');
        //  $('#Add_Services').hide();
    }
    else if (dd.selectedOptions[0].value == '2') {
        $('#Add_NonInventory').show();
        $('#Add_Services').hide();
        $('#Add_Inventory').hide();
    }
    else if (dd.selectedOptions[0].value == '3') {
        $('#Add_NonInventory').hide();
        $('#Add_Services').show();
        $('#Add_Inventory').hide();
    }

}
function DisableInventory() {

    $('#Add_Inventory').find('select').select2();
    $("#ddlType").select2();
    $('#Add_Inventory').find('input, textarea, button, select').attr('disabled', 'disabled');
    $("#Add_Inventory").find('select').select2('destroy');
    $('#Add_Inventory').find('input, textarea, button,select').css({ 'cssText': 'background: #dddddd !important' });
    $('#Add_Inventory').find(('.datepicker:input[type="text"]')).prop('disabled', true);
    $('.gj-icon').hide();
    $('a').attr('disabled', true);
    $("#ddlType").select2('destroy');
    $("#ddlType").attr('disabled', 'disabled');
    $("#ddlType").css({ 'cssText': 'background :#dddddd !important ' });
    $("#btnEditInventory").attr('disabled', false);
    $("#btnEditInventory").css({ 'cssText': 'background:' });
    $("#btnResetInventory").attr('disabled', false);
    $("#btnResetInventory").css({ 'cssText': 'background:' });
}
function EnableInventory() {
    $('#Add_Inventory').find('input, textarea, button, select').attr('disabled', false);
    $("#Add_Inventory").find('select').select2({ width: '100%' });

    //$("#ddlJournalOptions").select2()
    $('#Add_Inventory').find('input, textarea, button,select').css({ 'cssText': 'background ' });
    $("#ddlType").attr('disabled', 'disabled');
    $("#ddlType").css({ 'cssText': 'background :#dddddd !important ' });
    $('a').attr('disabled', false);
    $("#btnEditInventory").hide();
    if ($('#txtInitialQTY_Inventory').val() == "") {
        $("#txtAsOFDate_Inventory").attr('disabled', 'disabled');
        $("#txtAsOFDate_Inventory").css({ 'cssText': 'background: #dddddd !important' });
        $('#txtAsOFDate_Inventory').next().hide();
        $('#txtAsOFDate_Inventory').val('');
    }
    else
        $('.gj-icon').show();


}
function DisableNon_Inventory() {
    $('#Add_NonInventory').find('select').select2();
    $("#ddlType").select2();
    $('#Add_NonInventory').find('input, textarea, button, select').attr('disabled', 'disabled');
    $("#Add_NonInventory").find('select').select2('destroy');
    $('#Add_NonInventory').find('input, textarea, button,select').css({ 'cssText': 'background: #dddddd !important' });
    $('#Add_NonInventory').find(('.datepicker:input[type="text"]')).prop('disabled', true);
    $('.gj-icon').hide();
    $('a').attr('disabled', true);
    $("#ddlType").select2('destroy');
    $("#ddlType").attr('disabled', 'disabled');
    $("#ddlType").css({ 'cssText': 'background :#dddddd !important ' });
    $("#btnEditNonInventory").attr('disabled', false);
    $("#btnEditNonInventory").css({ 'cssText': 'background:' });
    $("#btnResetNonInventory").attr('disabled', false);
    $("#btnResetNonInventory").css({ 'cssText': 'background:' });
}
function EnableNon_Inventory() {

    $('#Add_NonInventory').find('input, textarea, button, select').attr('disabled', false);
    $("#Add_NonInventory").find('select').select2({ width: '100%' });

    //$("#ddlJournalOptions").select2()
    $('#Add_NonInventory').find('input, textarea, button,select').css({ 'cssText': 'background ' });

    $("#ddlType").attr('disabled', 'disabled');
    $("#ddlType").css({ 'cssText': 'background :#dddddd !important ' });
    $("#ddlType").attr('disabled', 'disabled');
    $("#ddlType").css({ 'cssText': 'background :#dddddd !important ' });
    $('a').attr('disabled', false);
    $("#btnEditNonInventory").hide();


}
function DisableServices() {
    $('#Add_Services').find('select').select2();
    $("#ddlType").select2();
    $('#Add_Services').find('input, textarea, button, select').attr('disabled', 'disabled');
    $("#Add_Services").find('select').select2('destroy');
    $('#Add_Services').find('input, textarea, button,select').css({ 'cssText': 'background: #dddddd !important' });
    $('#Add_Services').find(('.datepicker:input[type="text"]')).prop('disabled', true);
    $('.gj-icon').hide();
    $('a').attr('disabled', true);
    $("#ddlType").select2('destroy');
    $("#ddlType").attr('disabled', 'disabled');
    $("#ddlType").css({ 'cssText': 'background :#dddddd !important ' });
    $("#btnEditService").attr('disabled', false);
    $("#btnEditService").css({ 'cssText': 'background:' });
    $("#btnResetService").attr('disabled', false);
    $("#btnResetService").css({ 'cssText': 'background:' });
}
function EnableServices() {
    $('#Add_Services').find('input, textarea, button, select').attr('disabled', false);
    $("#Add_Services").find('select').select2({ width: '100%' });
    //$("#ddlJournalOptions").select2()
    $('#Add_Services').find('input, textarea, button,select').css({ 'cssText': 'background ' });
    //$("#ddlType").select2('destroy');
    $("#ddlType").attr('disabled', 'disabled');
    $("#ddlType").css({ 'cssText': 'background :#dddddd !important ' });
    $('a').attr('disabled', false);
    $("#btnEditService").hide();

}
function Reset_InventoryForm() {
    txtSKU_Inventory.value = "";
    txtName_Inventory.value = "";
    txtDesc_Inventory.value = "";
    ddlCatagory_Inventory.selectedIndex = 0
    $('#select2-ddlCatagory_Inventory-container').text('Select');
    txtInitialQTY_Inventory.value = "";
    ddlAssetAccount_Inventory.selectedIndex = 0;
    $('#select2-ddlAssetAccount_Inventory-container').text('Select');
    ddlIncomeAccount_Inventory.selectedIndex = 0;
    $('#select2-ddlIncomeAccount_Inventory-container').text('Select');

    txtUnit_Inventory.value = "";
    txtRate_Inventory.value = "";
    txtCost_Inventory.value = "";
    ddlSupplier_Inventory.selectedIndex = 0;
    $('#select2-ddlSupplier_Inventory-container').text('Select');
    txtImage_Inventory.value = "";

}
function Reset_Non_InventoryForm() {
    txtSKU_NonInventory.value = "";
    txtName_NonInventory.value = "";
    txtDesc_NonInventory.value = "";
    ddlCatagory_NonInventory.selectedIndex = 0;
    $('#select2-ddlCatagory_NonInventory-container').text('Select');
    txtUnit_NonInventory.value = "";
    txtRate_NonInventory.value = "";
    txtCost_NonInventory.value = "";
    ddlAccount_NonInventory.selectedIndex = 0;
    $('#select2-ddlAccount_NonInventory-container').text('Select');
    ddlExpenseAccount_NonInventory.selectedIndex = 0;
    $('#select2-ddlExpenseAccount_NonInventory-container').text('Select');
    ddlSupplier_NonInventory.selectedIndex = 0;
    $('#select2-ddlSupplier_NonInventory-container').text('Select');
    txtImage_NonInventory.value = "";

}
function ResetServiceForm() {
    txtSKU_Services.value = "";
    txtName_Services.value = "";
    txtDesc_Services.value = "";
    ddlCatagory_Service.selectedIndex = 0
    $('#select2-ddlCatagory_Service-container').text('Select');
    txtUnit_Services.value = "";
    txtRate_Services.value = "";
    txtCost_Services.value = "";
    ddlIncomeAccount_Service.selectedIndex = 0;
    $('#select2-ddlIncomeAccount_Service-container').text('Select');
    ddlExpenseAccount_Service.selectedIndex = 0;
    $('#select2-ddlExpenseAccount_Service-container').text('Select');
    ddlSupplier_Service.selectedIndex = 0;
    $('#select2-ddlSupplier_Service-container').text('Select');
    txtImage_Services.value = "";
}
function ValidateInventory() {
    if ($("#txtSKU_Inventory").val().match(AlphaNumericRegex)) {
    }
    else {
        showMessage('please enter SKU', 'danger', '');
        $("#txtSKU_Inventory").focus();
        return false;
    }
    if ($("#txtName_Inventory").val().match(AlphaNumericRegex)) {

    }
    else {
        showMessage('please enter Name', 'danger', '');
        $("#txtName_Inventory").focus();
        return false;
    }
    if ($("#ddlAssetAccount_Inventory").val() != 0) {
        show_confirmSave('are you print this');
    }
    else {
        showMessage('please select Asset Account', 'danger', '');
        $("#ddlAssetAccount_Inventory").focus();
        return false;
    }
}
function ValidateNonInventory() {
    if ($("#txtSKU_NonInventory").val().match(AlphaNumericRegex)) {
    }
    else {
        showMessage('please enter SKU', 'danger', '');
        $("#txtSKU_NonInventory").focus();
        return false;
    }
    if ($("#txtName_NonInventory").val().match(AlphaNumericRegex)) {
        show_confirmSave('are you print this');
    }
    else {
        showMessage('please enter Name', 'danger', '');
        $("#txtName_NonInventory").focus();
        return false;
    }

}
function ValidateServices() {
    if ($("#txtSKU_Services").val().match(AlphaNumericRegex)) {
    }
    else {
        showMessage('please enter SKU', 'danger', '');
        $("#txtSKU_Services").focus();
        return false;
    }
    if ($("#txtName_Services").val().match(AlphaNumericRegex)) {
        show_confirmSave('are you print this');
    }
    else {
        showMessage('please enter Name', 'danger', '');
        $("#txtName_Services").focus();
        return false;
    }

}
function show_confirmSave(message) {
    swal({
        title: "Do You Wish To",
        icon: "warning",
        buttons: {
            cancel: "Cancel",
            SaveAndPrint: "Save And Print",
            SaveOnly: "Save Only",
        },
    }).then((ifyes) => {
        if (ifyes) {

            //$("#ExpenseVoucher").hide();
            //$("#ExpenseVoucherEdit").hide();
            //jQuery('#div_ExpList').show();// Allow next click to succeed
            showMessage('Data Saved Successfully', 'success', '');
            setTimeout(function () { window.location.href = "http://localhost:42985/ProductAndServices.aspx"; }, 3000);
        }
    });
}
function ValidateInitialQtyOnHand() {
    if ($('#txtInitialQTY_Inventory').val() != '') {
        if ($('#txtInitialQTY_Inventory').val().match(RegexForPositiveIncludeZero)) {
            $("#txtAsOFDate_Inventory").attr('disabled', false);
            $("#txtAsOFDate_Inventory").css({ 'cssText': 'background: ' });
            $('#txtAsOFDate_Inventory').next().show();
            $('#txtAsOFDate_Inventory').val(GetTodayDate());
        }
        else {
            $('#txtInitialQTY_Inventory').val('');
        }

    }
    else {
        $("#txtAsOFDate_Inventory").attr('disabled', 'disabled');
        $("#txtAsOFDate_Inventory").css({ 'cssText': 'background: #dddddd !important' });
        $('#txtAsOFDate_Inventory').val('');
        $('#txtAsOFDate_Inventory').next().hide();
    }
}